language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
    - export FLASK_APP=run.py
    - psql -c 'create database testpolitico;' -U postgres  
    

services:
 - postgresql
  
script:
  - pytest --cov=app

after_success:
  - coveralls